### ISSUE TITLE
Sigue funcionado? 

### ISSUE THREAD

**Issue by l3utterfish** [mcorcuera/netflix-filmaffinity#2]
PArece qeu no

**Comment by mcorcuera** [comment]
Hola,

Acabo de publicar una nueva version, arreglando los errores. Disculpas por la tardanza :)

**Comment by l3utterfish** [comment]
Gracias por la actualización! Funcionando correctamente. 
Una sugerencia seria que aparezca en el menu de las películas... 
algo asi. https://i.gyazo.com/27e2abb4c0abb8a8b147fd4cbf1baac9.jpg
